bgp_peers:
  - peer_address: <ipv4/ipv6 peer address>
    remote_as: <peer AS>
    enabled: <true | false>
    solo: <true | false>
    password: <BGP MD5 password>
    peer_desc: <description>
    peer_group: <peer-group>
    capability:
      dynamic: <true | false>
      extended-next-hop: <true | false>
    advertisement_interval: <0-600>
    disable_capability_negotiation: <true | false>
    disable_capability_check: <true | false>
    ebgp_multihop: <number of hops>
    graceful_restart: <true | false>
    override_capability: <true | false>
    passive: <true | false>
    port: <peer bgp port>
    strict_capability_match: <true | false>
    timers:
      connect: <0-65535>
      holdtime: <0-65535>
      keepalive: <0-65535>
    ttl_security_hops: <1-254>
    update_source: <source IP address>
    local_as: <alternate AS to use with this peer>
      no_prepend: <true | false>
        replace_as: <true | false>
    interface:
      peer_group: <peer-group>
      remote_as: <peer AS>
      source_interface: <source interface>
      v6only: <true | false>
        peer_group: <peer group>
        remote_as: <peer AS | external | internal>
    bfd:
      profile: <profile name>
      check_control_plane_failure: <true | false>
    address_family:
      ipv4_flowspec: <true | false>
        filter_list:
          export: <AS-PATH-LIST>
          import: <AS-PATH-LIST>
        prefix_list:
          export: <PREFIX LIST>
          import: <PREFIX LIST>
        route_map:
          export: <route-map>
          import: <route-map>
        route_reflector_client: <true | false>
        route_server_client: <true | false>
        soft_reconfiguration: <true | false>
          inbound: <true | false>
      ipv4_labeled_unicast: <true | false>
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv4-multicast:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv4-unicast:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv4-vpn:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv6-flowspec:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv6-labeled-unicast:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv6-multicast:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv6-unicast:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv6-vpn:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      l2vpn-evpn:
        allowas-in: <true | false>
          number: <1-10>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        next-hop-self: <true | false>
          force: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
