bgp_peer_groups:
  - peer_group_name: <peer group name>
    remote_as: <peer AS>
    enabled: <true | false>
    password: <BGP MD5 password>
    peer_group_desc: <description>
    capability:
      dynamic: <true | false>
      extended-next-hop: <true | false>
    disable_capability_negotiation: <true | false>
    disable_capability_check: <true | false>
    ebgp_multihop: <number of hops>
    graceful_restart: <true | false>
    override_capability: <true | false>
    passive: <true | false>
    ttl_security_hops: <1-254>
    update_source: <source IP address>
    local_as: <alternate AS to use with this peer>
      no_prepend: <true | false>
        replace_as: <true | false>
    bfd:
      profile: <profile name>
      check_control_plane_failure: <true | false>
    address_family:
      ipv4-unicast:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      ipv6-vpn:
        addpath-tx-all: <true | false>
        addpath-tx-per-as: <true | false>
        allowas-in: <true | false>
          number: <1-10>
        as-override: <true | false>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        capability: <true | false>
          orf: <true | false>
            prefix-list: <true | false>
              send: <true | false>
              recieve: <true | false>
        conditionally-advertise: 
          advertise-map: <route-map>
          exist-map: <route-map>
          non-exist-map: <route-map>
        default-originate: <true | false>
        disable-send-community:
            standard: <true | false>
            extended: <true | false>
        distribute-list:
          export: <Access-list number>
          import: <Access-list number>
        filter-list:
          export: <AS PATH list>
          import: <AS PATH list>
        maximum-prefix: <#####>
        maximum-prefix-out: <#####>
        next-hop-self: <true | false>
          force: <true | false>
         prefix-list:
            export: <prefix list>
            import: <prefix list>
        remove-private-as: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>
        unsuppress-map: <route-map>
        weight: <1-65535>
      l2vpn-evpn:
        allowas-in: <true | false>
          number: <1-10>
        attribute-unchanged: <true | false>
          as-path: <true | false>
          med: <true | false>
          next-hop: <true | false>
        next-hop-self: <true | false>
          force: <true | false>
        route-map:
          export: <route-map>
          import: <route-map>
        route-reflector-client: <true | false>
        route-server-client: <true | false>
        soft-reconfiguration: <true | false>
          inbound: <true | false>